name: Deploy Next.js to GitHub Pages

on:
  push:
    branches:
      - main # Or your default branch
  workflow_dispatch: # Allow manual triggering

jobs:
  build-and-deploy: # Job name can be kept or changed
    runs-on: ubuntu-latest
    permissions:
      contents: read # Changed from write
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Specify your Node.js version

      - name: Install dependencies
        run: npm ci # Use ci for cleaner installs

      - name: Build Next.js app
        run: npm run build
        env:
          NEXT_PUBLIC_BASE_PATH: /weco-concept-explorer # Pass base path as env var

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

      - name: Deploy to GitHub Pages
        id: deployment # id is important for accessing the output URL
        uses: actions/deploy-pages@v4