name: Deploy Next.js to GitHub Pages

on:
  push:
    branches:
      - main # Or your default branch
  workflow_dispatch: # Allow manual triggering

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write # To push to gh-pages
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Specify your Node.js version

      - name: Install dependencies
        run: npm ci # Use ci for cleaner installs

      - name: Build Next.js app
        run: npm run build
        env:
          NEXT_PUBLIC_BASE_PATH: /weco-concept-explorer # Pass base path as env var if needed by your app

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          # cname: your-custom-domain.com # Optional: if you have a custom domain
